Logger
scottcorgan/pushstate-server pull request #46
Opened 2017-01-30 19:57 UTC by evantahler

It's generally useful for your web servers to have logs!

<img width="889" alt="screen shot 2017-01-30 at 11 55 17 am" src="https://cloud.githubusercontent.com/assets/303226/22439098/3ae4ea16-e6e3-11e6-8f89-346324d3942c.png">

2017-01-30 19:57 UTC, evantahler commented
Closes https://github.com/scottcorgan/pushstate-server/issues/41

2017-02-02 23:07 UTC, scottcorgan commented
Can you elaborate just a bit on your choice of vocabulary used in the api (such as `appenders`)?

2017-02-03 01:31 UTC, evantahler commented
The vocabulary comes from https://github.com/nomiddlename/log4js-node.  An `appender` is basically an output of the logger... it might be to the console (stdio), it might be to a file, it might be to some logging service.   I'll bet for 90% of the use-cases for this server, logging to only console is OK.

2017-02-06 12:53 UTC, scottcorgan requested changes
Just a few comments on the code.

Also, I like to take the safe approach and be explicit about default and custom configurations (from my Elm experience).

What do you think about the following APIs?

```js
// Deafults to 'ALL' and 'console'
server.start({
  logger: true
});

// Allows you to configure to how you'd like?
server.start({
  customLogger: {
    level: 'All',
    appenders: [
      { type: 'console' }
    ]
  }
});
```

2017-02-06 12:53 UTC, scottcorgan commented on index.js
> +  // configure logger
Should probably only use the logger if they provide a config for it (not default to all the time)

2017-02-06 12:53 UTC, scottcorgan commented on package.json
> +    "log4js": "^1.1.0",
Go ahead and lock the dependency here to the latest current version. (I locked the dependencies recently to avoid any unknown breaking changes)

2017-02-06 17:21 UTC, evantahler commented
I tend to prefer that logging is enabled by default... but OK! 
Version locked and disabled by default :D

2017-02-08 14:36 UTC, scottcorgan requested changes
Just a couple more changes. I have to be picky with this because it's used by some big projects and I don't want to break those projects.

Thanks!

2017-02-08 14:36 UTC, scottcorgan commented on README.md
> +});
Sorry, just a couple more changes, then it's ready to merge! 🎉 . Should probably add an example here of using a logger default values.

2017-02-08 14:36 UTC, scottcorgan commented on index.js
> +const LOGGEROPTIONS = {}
I think the default value for this should be false. Then we could check if it's true or an object, then attach the logger.

2017-09-15 08:06 UTC, lukaspj commented
Any updates on this feature?

2017-09-15 15:44 UTC, scottcorgan commented
@lukaspj can you move conversation to https://github.com/scottcorgan/pushstate-server/issues/41?

Thanks 👍

2026-05-07 02:19 UTC, closed without merging